### PR TITLE
Disable HashAsLastArrayItem style

### PR DESCRIPTION
**Pull request by lsanchezv33**
# Changes

- Disable HashAsLastArrayItem style to control error in the `permitted_params` files

```
risk_underwriting_data: {},
price_formula: {},...
```

## Checks
- [X] Create a small and one-feature pull request.
- [X] Add and/or update the related documentation.
- [X] Ensure you have written good tests :heart:
- [X] Rubocop passes
- [X] Assign yourself and your direct collaborators to the pull request.
- [X] Request the reviewers, they are gonna help you to improve your code.
- [X] Add the [right labels](https://github.com/monokera-tech/it-guidelines#good-practices).

### CODE REVIEW

**Review by juannicolasvargas — APPROVED** [review]

**Review by crmendoza093 — APPROVED** [review]

**Review by haroldpineda — APPROVED** [review]

**Review by andrespxr — COMMENTED** [review]
Why disable it?
Better adjust it to the way we use

**Comment by lsanchezv33** [comment]
> Why disable it?
> Better adjust it to the way we use

@andrespxr At this moment the linter does not pass because raise the error about this code, `lines 14 and 27`, so, in these lines what values we could add to these params or only add the `# rubocop disable Style/HashAsLastArrayItem` and reply to this comment in other services to control this linter?

Screen Shot 2021-03-02 at 10 37 52

**Comment by andrespxr** [comment]
I know what the error is, what I am saying is that instead of "Disable", the Cop must be adjusted so that it is taken correctly.

**Review by ajalvarez89 — APPROVED** [review]

**Comment by lsanchezv33** [comment]
> I know what the error is, what I am saying is that instead of "Disable", the Cop must be adjusted so that it is taken correctly.

Okey, @andrespxr handle the style like `EnforcedStyle: braces` and remove `Enable: false`, right?

**Comment by andrespxr** [comment]
```yml
- EnforcedStyle: no_braces
```

**Comment by lsanchezv33** [comment]
> ```yaml
> - EnforcedStyle: no_braces
> ```

Yes, my fault, `no_braces`

**Review by andrespxr — APPROVED** [review]

**Pull request merged**
